ALTER TABLE "Payout" ADD COLUMN "reminderSentAt" TIMESTAMP(3);
ALTER TYPE "NotificationType" ADD VALUE 'PAYOUT_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE 'PAYOUT_DUE';
ALTER TYPE "NotificationType" ADD VALUE 'PAYOUT_FROZEN';
ALTER TYPE "NotificationType" ADD VALUE 'PAYOUT_RESUMED';
ALTER TABLE "Payout" ADD COLUMN "refundRequired" BOOLEAN NOT NULL DEFAULT false;
