import { beforeEach, expect, it, vi } from "vitest";
import { renderToStaticMarkup } from "react-dom/server";
import { StaticRouter } from "react-router-dom/server";
import { TeamPanel } from "../pages/TeamPanel";
const auth = vi.hoisted(() => ({ user: null as null | { id: string; role: string }, loading: false }));
vi.mock("./AuthContext", () => ({ useAuth: () => auth }));
vi.mock("react-router-dom", async (original) => ({ ...await original<typeof import("react-router-dom")>(), Navigate: ({ to }: { to: string }) => <div data-redirect={to} /> }));
vi.mock("../components/teamPanel/PanelSidebar", () => ({ PanelSidebar: () => <div>Menú interno</div> }));
vi.mock("../components/teamPanel/PanelSection", () => ({ PanelSection: ({ slug }: { slug: string }) => <section>{slug}</section> }));
vi.mock("../components/SuspensionBanner", () => ({ SuspensionBanner: () => null }));
const render = (path = "/panel/casos") => renderToStaticMarkup(<StaticRouter location={path}><TeamPanel /></StaticRouter>);
beforeEach(() => { auth.user = { id: "staff", role: "admin" }; auth.loading = false; });
it("arranque de pestaña nueva espera sesión sin mostrar controles", () => { auth.loading = true; const out = render(); expect(out).toContain("Cargando panel"); expect(out).not.toContain("Menú interno"); });
it("anónimo va a actividad sin contenido staff", () => { auth.user = null; expect(render()).toContain('data-redirect="/actividad"'); expect(render()).not.toContain("casos"); });
it.each(["student", "creator"])("rol %s va a actividad incluso por ruta directa", (role) => { auth.user = { id: "u", role }; expect(render()).toContain('data-redirect="/actividad"'); expect(render()).not.toContain("Menú interno"); });
it("panel tiene main único y scroll propio sin cabecera/footer públicos", () => { const out = render(); expect((out.match(/<main/g) ?? [])).toHaveLength(1); expect(out).toContain("overflow-y-auto"); expect(out).toContain("h-dvh"); expect(out).not.toContain("Buscar en el catálogo"); expect(out).not.toContain("Marco legal"); });
it("trabajador que abre Miembros directamente vuelve al resumen", () => { auth.user = { id: "worker", role: "moderator" }; expect(render("/panel/miembros")).toContain('data-redirect="/panel/resumen"'); });
it("Técnico sí obtiene Miembros", () => { expect(render("/panel/miembros")).toContain("<section>miembros</section>"); });
it("sección desconocida ofrece enlace al resumen", () => { const out = render("/panel/desconocida"); expect(out).toContain("Sección no disponible"); expect(out).toContain('/panel/resumen'); });
